language: php

php:
  - 7.0
  - 7.1
  - 7.2

# This triggers builds to run on the new TravisCI infrastructure.
# See: http://docs.travis-ci.com/user/workers/container-based-infrastructure/
sudo: false

## Cache composer
cache:
  directories:
    - $HOME/.composer/cache

env:
  global:
    - setup=basic

matrix:
  include:
    - php: 7.0
      env: setup=lowest

install:
  - if [[ $setup = 'basic' ]]; then travis_retry composer install --prefer-dist --no-interaction; fi
  
script: vendor/bin/phpcs --standard=PSR2 src && vendor/bin/phpunit --coverage-text
